//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MImpCfg.rc
//
#define IDAPPLY                         3
#define IDD_MAIN_DIALOG                 103
#define IDC_HAND_CURSOR                 106
#define IDR_MAINFRAME                   128
#define IDD_ABOUT_PAGE                  129
#define IDD_SCROLL_PAGE                 130
#define IDD_WND_PATT_DLG                131
#define IDB_LIST_ARROW_BMP              132
#define IDD_WND_PAT_SEL_DLG             133
#define IDI_WND_FIND_ICON               134
#define IDI_WND_EMPTY_ICON              135
#define IDC_WND_FIND_CUR                136
#define IDD_ODOMETER_DLG                138
#define IDB_TV4_LOGO_BMP                140
#define IDD_GENERAL_DLG                 148
#define IDB_CHECK_BMP                   150
#define IDR_CONTEXT_MENU                151
#define IDR_LOGO1_PNG                   152
#define IDR_LOGO2_PNG                   153
#define IDR_TITLE_LOGO_PNG              158
#define IDB_PATT_TYPE_BMP               159
#define IDD_REG_INFO_DLG                160
#define IDD_SHOW_NEWS_DLG               172
#define IDR_QUICK1_PNG                  173
#define IDR_QUICK2_PNG                  174
#define IDR_QUICK3_PNG                  175
#define IDR_QUICK4_PNG                  176
#define IDR_QUICK5_PNG                  177
#define IDR_QUICK6_PNG                  178
#define IDD_QUICK_TOUR_DLG              179
#define IDR_QUICK0_PNG                  182
#define IDC_MOUSE_DIST_EDIT             1000
#define IDC_MOUSE_SAVED_EDIT            1001
#define IDC_ASHRINK_SAVED_EDIT          1002
#define IDC_CTRL_KEY_COMBO              1003
#define IDC_ELAPSED_TIME_EDIT           1003
#define IDC_WND_PAT_LIST                1005
#define IDC_INS_BTN                     1006
#define IDC_DEL_BTN                     1007
#define IDC_APP_EDIT                    1008
#define IDC_EDIT_BTN                    1008
#define IDC_CLASS_EDIT                  1009
#define IDC_TITLE_EDIT                  1010
#define IDC_CAPTURE_STATIC              1011
#define IDC_RESET                       1016
#define IDC_LOGO_BMP_STATIC             1017
#define IDC_CHILD_TAB                   1018
#define IDC_INV_CHECK                   1019
#define IDC_RED_EDIT                    1020
#define IDC_RED_SPIN                    1021
#define IDC_NORM_RED_EDIT               1023
#define IDC_REDUCT_KEY_COMBO            1024
#define IDC_ENABLED_CHECK               1025
#define IDC_HIDE_TIME_EDIT              1026
#define IDC_HIDE_TIME_SPIN              1027
#define IDC_HIDE_CHECK                  1031
#define IDC_TITLE_LOGO_STATIC           1032
#define IDC_APP_NAME_ALL_CHECK          1033
#define IDC_WND_CLASS_ALL_CHECK         1034
#define IDC_WND_NAME_ALL_CHECK          1035
#define IDC_USE_CURSOR_CHECK            1036
#define IDC_RUN_AT_START_CHECK          1037
#define IDC_DISABLE_KEY_COMBO           1039
#define IDC_IE_MOVE_SENS_EDIT           1043
#define IDC_IE_MOVE_SENS_SPIN           1044
#define IDC_TICON_ENABLE_CHECK          1045
#define IDC_VER_EDIT                    1046
#define IDC_SEL_HOTKEY                  1047
#define IDC_FIND_BTN                    1048
#define IDC_TYPE_COMBO                  1050
#define IDC_SPLASH_SHOW_CHECK           1051
#define IDC_KEY_EDIT                    1053
#define IDC_TICON_ENABLE_ANIM_CHECK     1054
#define IDC_BD_SCROLL_CHECK             1055
#define IDC_NORM_RED_SPIN               1076
#define IDC_CONTROL_TYPE_COMBO          1078
#define IDC_DELAY_OPEN_EDIT             1079
#define IDC_DELAY_OPEN_SPIN             1080
#define IDC_DELAY_OPEN_CHECK            1081
#define IDC_NEWS_EDIT                   1084
#define IDC_GO_BTN                      1085
#define IDC_IMG_STATIC                  1087
#define IDC_NEXT_BTN                    1089
#define IDC_PREV_BTN                    1090
#define IDC_TRAY_CLICK_COMBO            1092
#define IDC_LNK_COPY                    32771
#define IDC_LNK_OPEN                    32772
#define IDS_MSG_HOST_NOT_START          0xbf00
#define IDS_STR_KEY_LBUTTON             48897
#define IDS_STR_KEY_MBUTTON             48898
#define IDS_STR_KEY_RBUTTON             48899
#define IDS_STR_KEY_CTRL                48900
#define IDS_STR_KEY_SHIFT               48901
#define IDS_STR_KEY_ALT                 48902
#define IDS_STR_PIRATES                 48903
#define IDS_COL_APP                     48904
#define IDS_COL_CLASS                   48905
#define IDS_COL_TITLE                   48906
#define IDS_STR_KM_MT_CM_MM             48907
#define IDS_STR_MT_CM_MM                48908
#define IDS_STR_CM_MM                   48909
#define IDS_STR_MASK_ALL                48910
#define IDS_STR_SH_ODM_MASK             48911
#define IDS_COL_APATT_FULL_NAME         48912
#define IDS_COL_APATT_EXE_NAME          48913
#define IDS_STR_VER_MASK                48914
#define IDS_MSG_INV_VER                 48915
#define IDS_MSG_REG_HOTKEY_FAILED       48916
#define IDS_MSG_POP_FIND_INSTR          48917
#define IDS_STR_ST_SHRINK               48918
#define IDS_STR_ST_ACTIVATE             48919
#define IDS_MSG_UNREG_NOTE              48920
#define IDS_MSG_WEB_CHECK_NO_NEW_INFO   48921
#define IDS_MSG_REG_THANK               48922
#define IDS_STR_SCR_CTYPE_MIX           48923
#define IDS_STR_SCR_CTYPE_STANDARD      48924
#define IDS_STR_SCR_CTYPE_TOGGLE        48925
#define IDS_STR_TICON_CMODE_NONE        48926
#define IDS_STR_DAY_HOR_MIN_SEC         48927
#define IDS_STR_HOR_MIN_SEC             48928
#define IDS_STR_MIN_SEC                 48929
#define IDS_STR_TICON_CMODE_DIRECTSCROLL 48930
#define IDS_STR_TICON_CMODE_AUTOHIDE    48931

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        189
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
